[pytest]
DJANGO_SETTINGS_MODULE = sqip.settings
python_files = test_*.py *_tests.py
# Ignore the project's virtualenv/site-packages to avoid collecting third-party package tests
addopts = --ignore=lib -s