# Generated by Django 5.0.1 on 2024-01-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="display_picture",
            field=models.ImageField(blank=True, upload_to="display_picture"),
        ),
    ]
