# Generated by Django 5.0.1 on 2024-01-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_organization_display_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="type",
            field=models.CharField(
                choices=[
                    ("restaurant", "Restaurant"),
                    ("clinic", "Clinic"),
                    ("doctor", "Doctor"),
                ],
                max_length=20,
            ),
        ),
    ]
