# Generated by Django 5.1.2 on 2024-10-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_profile_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x10ae96480>", max_length=200
            ),
        ),
    ]
