# Generated by Django 5.0.1 on 2024-01-11 14:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_organization_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
