# Generated by Django 5.0.1 on 2024-01-11 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_appointment_category_appointment_date_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="created_by",
            new_name="user",
        ),
    ]
