# Generated by Django 5.1.2 on 2024-11-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_category_group_alter_profile_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x10d6fe480>", max_length=200
            ),
        ),
    ]
