# Generated by Django 5.0.1 on 2024-01-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_rename_created_by_appointment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="counter",
            field=models.IntegerField(default=0),
        ),
    ]
