# Generated by Django 5.0.1 on 2024-01-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_appointment_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="counter",
            field=models.IntegerField(),
        ),
    ]
