# Generated by Django 5.0.8 on 2024-11-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_appointment_created_by_appointment_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x10d2ab9c0>", max_length=200
            ),
        ),
    ]
