# Generated by Django 5.0.8 on 2024-11-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_category_name_alter_profile_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x10d9af9c0>", max_length=200
            ),
        ),
    ]
