# Generated by Django 5.0.8 on 2024-11-26 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_profile_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="scheduled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="break_hours",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="category",
            name="is_scheduled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="opening_hours",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="category",
            name="time_interval_per_appointment",
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x10b5ab9c0>", max_length=200
            ),
        ),
    ]
