# Generated by Django 5.0.1 on 2024-01-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_appointment_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="estimated_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="scheduled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("checkin", "CheckIn"),
                    ("cancel", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
