# Generated by Django 5.0.8 on 2024-11-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_category_time_zone_alter_profile_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="max_advance_days",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Maximum number of days in the future an appointment can be scheduled.",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="break_hours",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x10d0b39c0>", max_length=200
            ),
        ),
    ]
