# Generated by Django 5.0.1 on 2024-01-26 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0010_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="group",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="auth.group"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x1089de200>", max_length=200
            ),
        ),
    ]
