# Generated by Django 5.1.2 on 2024-11-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_category_max_advance_days_alter_category_break_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="scheduled_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="max_advance_days",
            field=models.PositiveIntegerField(
                blank=True,
                default=7,
                help_text="Maximum number of days in the future an appointment can be scheduled.",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="opening_hours",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "General"),
                    ("inperson", "In Person"),
                    ("drive-thru", "Drive-thru"),
                    ("online", "Online"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x10f72a840>", max_length=200
            ),
        ),
    ]
