# Generated by Django 4.2.27 on 2026-03-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_appointment_scheduled_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('checkin', 'CheckIn'), ('checkout', 'CheckOut'), ('cancel', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x105d80430>', max_length=200),
        ),
    ]
