# Generated by Django 5.1.2 on 2024-10-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_category_estimated_time_alter_profile_uid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="scheduled",
            new_name="is_scheduled",
        ),
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x10f202840>", max_length=200
            ),
        ),
    ]
