# Generated by Django 5.1.2 on 2024-10-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_alter_appointment_counter_alter_appointment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("checkin", "CheckIn"),
                    ("cancel", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x10f402840>", max_length=200
            ),
        ),
    ]
