# Generated by Django 5.1.2 on 2024-10-27 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0016_alter_organization_created_by_alter_profile_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x10f7fa480>", max_length=200
            ),
        ),
    ]
