# Generated by Django 4.2.27 on 2026-03-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_add_org_admin_and_org_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x10a0b0430>', max_length=200),
        ),
    ]
