# Generated by Django 5.1.2 on 2024-10-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_alter_organization_group_alter_profile_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="type",
            field=models.CharField(
                choices=[
                    ("restaurant", "Restaurant"),
                    ("clinic", "Clinic"),
                    ("doctor", "Doctor"),
                    ("company", "Company"),
                    ("store", "Store"),
                    ("home", "Home"),
                    ("bank", "Bank"),
                    ("ATM", "ATM"),
                    ("school", "School"),
                    ("factory", "Factory"),
                    ("others", "Others"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x10b1fa480>", max_length=200
            ),
        ),
    ]
