# Generated by Django 4.2.27 on 2026-03-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_add_max_scheduled_per_user_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x106528430>', max_length=200),
        ),
    ]
