# Generated by Django 4.2.27 on 2026-03-21 20:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='address_line1',
            field=models.CharField(blank=True, default='', help_text='Location-specific street address (overrides org address if set)', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='address_line2',
            field=models.CharField(blank=True, default='', help_text='Floor, suite, landmark, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Location-specific contact number (overrides org phone if set)', max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_line1',
            field=models.CharField(blank=True, default='', help_text='Street address / building number', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_line2',
            field=models.CharField(blank=True, default='', help_text='Floor, suite, landmark, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Primary contact number for this organization (E.164 format, e.g. +911234567890)', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='category',
            name='estimated_time',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated time per appointment in minutes. Used to calculate wait time for walk-in queues.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x1067ac430>', max_length=200),
        ),
    ]
