# Generated by Django 4.2.27 on 2026-03-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_add_address_phone_to_org_category_fix_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pincode',
            field=models.CharField(blank=True, default='', help_text='Postal / ZIP code', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='pincode',
            field=models.CharField(blank=True, default='', help_text='Postal / ZIP code', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x108b30430>', max_length=200),
        ),
    ]
