# Generated by Django 4.2.27 on 2026-03-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_add_pincode_to_org_and_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='display_picture_base64',
            field=models.TextField(blank=True, default='', help_text='Base64-encoded data URL for the display picture (preferred over ImageField path).'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x108b08430>', max_length=200),
        ),
    ]
