# Generated by Django 4.2.27 on 2026-03-21 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_add_display_picture_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x10859c430>', max_length=200),
        ),
        migrations.CreateModel(
            name='AppointmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', help_text='Text body of the note.')),
                ('file_data', models.TextField(blank=True, default='', help_text='Base64-encoded file content (data URL). Leave empty if no file.')),
                ('file_name', models.CharField(blank=True, default='', help_text='Original filename for the attachment.', max_length=255)),
                ('file_mime', models.CharField(blank=True, default='', help_text='MIME type of the attachment (e.g. application/pdf).', max_length=100)),
                ('is_admin_note', models.BooleanField(default=False, help_text='True if added by a category admin; False if added by the booking user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_notes', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.appointment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
